### ISSUE TITLE
Quarto breaks if "PYTHONINSPECT=1"

### ISSUE THREAD

**Issue by Rotendahl** [quarto-ext/shinylive#17]
When setting up this awesome extension, __and installing everything__. 
I found that my setup broke with the error:
```txt
SystemExit: 0
ERROR: Error running 'shinylive' command. Perhaps you need to install the 'shinylive' Python package?
```

I determined that the error occurs when the quarto environment has `PYTHONINSPECT=1` as suggested in the [docs](https://quarto.org/docs/projects/environment.html#local-environment) 

Removing this caused everything to work. 

No clue why this happens, but posting workaround for the benefits of others.

**Comment by wch** [comment]
Interesting -- I'm able to reproduce the same problem. I wonder if it has a different `PATH`.

**Comment by wch** [comment]
Thanks for reporting this. I think this was just a bad choice of examples on the documentation page, and the example should be changed.. See https://github.com/quarto-dev/quarto-cli/issues/6606 for more information.

**Comment by Rotendahl** [comment]
Nice catch in https://github.com/quarto-dev/quarto-cli/issues/6606, I'll close this and remove the inspect thing from my env.
