### ISSUE TITLE
List of components and creating custom components

### ISSUE THREAD

**Issue by fredguth** [quarto-ext/shinylive#56]
I couldn't find the code that given
````
#| components: [editor, viewer]

`````
renders the editor.  I wish to tweak it to create a SQL code editor.  How could I do that?

**Comment by gadenbuie** [comment]
> Would it be possible to also create a textarea that is a code input? So that I can use it in any module?

That's a great idea and something we'll certainly consider building in the future! 

In Shiny for R, the [shinyAce package](https://trestletech.github.io/shinyAce/) provides a Shiny code editor component. I'd personally love to have a CodeMirror or Monaco component for Shiny for Python. 

If anyone in the community wants to work on this, the [Custom JavaScript component article series](https://shiny.posit.co/py/docs/custom-component-one-off.html) is a good place to start learning about the Shiny side of this kind of extension.

**Comment by fredguth** [comment]
I managed to make a js component that works with SQL highlight using CodeMirror. But the wrapped Shiny component does not load the js.

I am not sure I understood how to add dependencies:

https://github.com/fredguth/shiny-cm6/blob/f0aa9749b0bb8c15a90304366a555a0a0887c5a6/app.py#L7
